### ISSUE TITLE
Package names cannot contain "_"

### ISSUE THREAD

**Issue by DerMambo** [DispatchMe/mgp#27]
Would love to use mgp, but after adding the package to "git-packages.json" it downloads it and creates the folder like this "my_private-package".

I then get:

````
/PATH/TO/PROJECT/.meteor/packages: Package
   names can only contain lowercase ASCII alphanumerics, dash, dot, or colon,
   not "_".
````

Any idea on this?

**Comment by jperl** [comment]
What OS are you using?

**Comment by aldeed** [comment]
@DerMambo, in the package.js for the package, make sure `Package.describe` includes a name. And make sure that name matches the rules in that error message.

Folder name is used as the package name if not explicitly given, and since mgp replaces colons with underscores, the folder name is not a valid pkg name.

**Comment by DerMambo** [comment]
The name-tag did the trick, thx @aldeed!

@jperl it is MacOS.
